name: CI
on:
  pull_request:
  push:
    branches:
      - "**"
env:
  TZ: Asia/Shanghai

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: yanhao98/composite-actions/setup-node-environment@main
      - run: pnpm test
      - run: pnpm build
      - run: pnpx pkg-pr-new publish
      # - run: pnpx pkg-pr-new publish --compact # https://github.com/stackblitz-labs/pkg.pr.new?tab=readme-ov-file#setup
